A/A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

A/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', views.UserEditView.as_view(), name='user_edit'),
]

A/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('comment/reply/<int:post_id>/<int:comment_id>/', views.CommentAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

A/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post_User(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Model Meta options
    class Meta:
        ordering = ('-created',)

    # Model methods
    def __str__(self):
        return f'{self.user} - {self.slug}'

    def get_absolute_url(self):
        return reverse('home:post_detail', args=(self.id, self.slug))

    def get_absolute_url2(self):
        return reverse('account:user_profile', args=(self.id))
    
    def like_count(self):
        return self.plike.count()
    
    def user_can_like(self, user):
        user_like = user.ulike.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post_User, on_delete=models.CASCADE, related_name='pcomment')
    body = models.TextField(max_length=400)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomment', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return f'{self.user} - {self.body[:30]}'



class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulike')
    post = models.ForeignKey(Post_User, on_delete=models.CASCADE, related_name='plike')


    def __str__(self):
        return f'{self.user} Like {self.post.slug}'

A/home/forms.py
from django import forms
from .models import Post_User, Comment


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Post_User
        fields = ('body',)

class CreateForm(forms.ModelForm):
    class Meta:
        model = Post_User
        fields = ('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widget = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class PostSearchForm(forms.Form):
    search = forms.CharField()

A/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post_User, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import UpdateForm, CreateForm, CommentCreateForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        post = Post_User.objects.all()
        if request.GET.get('search'):
            post = post.filter(body__contains=request.GET['search'])
        return render(request, 'home/index.html', {'post':post, 'form':self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post_User, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)


    def get(self, request, post_id, post_slug):
        comment = self.post_instance.pcomment.filter(is_reply=False)
        #comment = Comment.objects.filter(post=post, is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return render(request, 'home/detail.html', {'post':self.post_instance, 'comment':comment, 
        'form':self.form_class,'reply_form':self.form_class_reply, 'can_like':can_like})

    @method_decorator(login_required)
    def post(self, request, post_id, post_slug):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.post = self.post_instance
            new_form.save()
            messages.success(request, 'your comment submitted successfully', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post_User, pk=post_id)
        if request.user.id == post.user.id:
            post.delete()
            messages.success(request, 'post deleted successfully', 'success')
        else:
            messages.error(request, 'you cant delete this post', 'danger')
        return redirect('home:home')

class PostUpdateView(LoginRequiredMixin, View):
    form_class = UpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post_User, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'you cant update this post', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, post_id):
        post = self.post_instance
        form = self.form_class(instance= post)
        return render(request, 'home/update.html', {'form':form})
        
    def post(self, request, post_id):
        post = self.post_instance
        form = self.form_class(request.POST, instance= post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'you updated this post', 'success')
            return redirect('home:post_detail', post.id, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = CreateForm

    def get(self, request):
        form = self.form_class()
        return render(request, 'home/create.html', {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'you created a new post', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)



class CommentAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post_User, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply submitted successfully', 'success')
        return redirect('home:post_detail', post.id , post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post_User, pk=post_id)
        like = Like.objects.filter(user= request.user, post=post)
        if like.exists():
            messages.error(request, 'you have already liked this post', 'danger')
        else:
            Like.objects.create(user= request.user, post=post)
            messages.success(request, 'you liked this post successfully', 'success')
        return redirect('home:post_detail', post.id, post.slug)

A/home/templates/home/create.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

A/home/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}
    <p><a href="{% url 'account:user_profile' post.user.id %}">{{ post.user }}</a> - {{ post.updated|date:"Y-M-d" }}</p>
    <p>{{ post.body }}</p><hr>
    
    {% if request.user.is_authenticated %}

        <a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} btn btn-primary col-md-1">Like {{ post.like_count }}</a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form><br>
    {% else %}
        <p class="alert alert-danger">only logged in users can comment</p>
    {% endif %}

    {% for comments in comment %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comments.user }} | {{ comments.created|timesince }}</p>
            <p class="card-body">{{ comments.body }}</p>

            {% if request.user.is_authenticated %}
                <form action="{% url 'home:add_reply' post.id comments.id %}" method="post">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="Send">
                </form>
            {% endif %}

            {% with replies=comments.rcomment.all %}
                {% for reply in replies %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }}<br/>{{ reply.body }}</p>
                {% endfor %}
            {% endwith %}

        </div><br>

    {% empty %}  
       <p>no comment yet!</p>
    {% endfor %}

{% endblock %}

A/home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}

    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
    
    <div class="card">
        {% for posts in post %}
            <a href=''> {{ posts.user }}</a>
            <a href="{{ posts.get_absolute_url }}"> {{ posts.body|truncatewords:8 }}</a><hr>
        {% endfor %}
    </div>
    

{% endblock %}

A/home/templates/home/update.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}